
---
:'1':
  :gravity: 'Northeast'
  :pointsize: 82
  :fill: '#cccccc'
  :stroke: '#000000'
:'2':
  :gravity: 'East'
  :pointsize: 82
  :fill: '#cccccc'
  :stroke: '#000000'
:'3':
  :gravity: 'South'
  :pointsize: 82
  :fill: '#cccccc'
  :stroke: '#000000'
:'4':
  :gravity: 'East'
  :pointsize: 82
  :fill: '#cccccc'
  :stroke: '#000000'
:'5':
  gravity': 'Southeast'
  :pointsize: 82
  :fill: '#cccccc'
  :stroke: '#000000'
:'6':
  :gravity: 'Center'
  :pointsize: 82
  :fill: '#cccccc'
  :stroke: '#000000'
:'7':
  :gravity: 'West'
  :pointsize: 82
  :fill: '#cccccc'
  :stroke: '#000000'
:'8':
  :gravity: 'East'
  :pointsize: 82
  :fill: '#cccccc'
  :stroke: '#000000'
:'9':
  :gravity: 'Southeast'
  :pointsize: 82
  :fill: '#000000'
  :stroke: '#cccccc'
:'10':
  :gravity: 'East'
  :pointsize: 82
  :fill: '#000000'
  :stroke: '#cccccc'
:'11':
  :gravity: 'North'
  :pointsize: 82
  :fill: '#cccccc'
  :stroke: '#000000'
:'12':
  :gravity: 'Center'
  :pointsize: 82
  :fill: '#cccccc'
  :stroke: '#000000'
